#!/bin/bash
# Created by Selloyd Fernandes

echo -e "\033c" 

echo "Created By Selloyd"

echo "Mounting Disks ...."
diskutil mountDisk /dev/disk4
diskutil mountDisk /dev/disk5
diskutil mountDisk /dev/disk6
diskutil mountDisk /dev/disk7
diskutil mountDisk /dev/disk8
echo "Disks Mounted"

echo "Launching Application ....."
/Volumes/BLANCCO/BEAD\ Agent/BEAD\ Agent.app/Contents/MacOS/BEAD\ Agent

exit 0
